# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5166cd99a94c4a0fb67b50059e9b2568475aa232e9c902dbf39091b7fe10d275742fd3760fbca352b28ca896276f238510b308b79831e67d55ca32c2cc424c9

test:
  secret_key_base: b94288c38b536bf63edb0d8a5ffd2082218f90a356cb54f8c9120fc34c0cdd7206c5789e253a6d191ef4decb729727390c549245fe64d09197383b8501cf4cbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
